# Other stuff:
#
#  config:
#    install_missing_compilers: true
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                             #
# COMMON                                                                      #
#                                                                             #
# - Settings that are common to the whole stack;                              #
# - These may later be declared in a separate file;                           #
# - This is kinda per architecture settings;                                  #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
common:
  metadata:
    section: common
  filters:
    gpu: nvidia
    python: 2
    mpi: ethernet
  variables:
    core_compiler: gcc@8.5.0
    cuda_arch: 70
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                             #
# PROGRAMMING ENVIRONMEMT SECTION (PE)                                        #
#                                                                             #
# - The name of each entry in this file have no impact on the processing      #
# - Each entry will be compiled (...)                                         #
# - The absence of the active key is equivalent to true                       #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
core:
  metadata:
    section: pe
  compiler: <core_compiler>
intel:
  metadata:
    section: pe
  stable:
    compiler: intel@19.1.2
    mpi: intel-mpi@2019.9.304
    blas: intel-mkl2019.5.281
    gpu:
      nvidia: cuda@11.6.2 cuda_arch=<cuda_arch>
      amd: rocm@2
    python: python@3.9.12 +tkinter +optimization
    cmake: 3.2.1
gcc:
  metadata:
    section: pe
  stable:
    compiler: gcc@9.3.0
    mpi:
     infiniband: mvapich2 fabrics=mrail @2.3.6
     ethernet:  mvapich2 fabrics=tcp,self @2.3.6
    blas: openblas@0.3.19
    gpu: cuda@10.2.89
    python: python@3.9.12 +tkinter +optimization
  nextgen:
    compiler: gcc@10.3.0
    mpi: mvapich2@2.3.7
    blas: openblas@0.3.20
    gpu:
      nvidia: cuda@1
      amd: rocm@2
    python: python@3.9.12 +tkinter +optimization
llvm:
  metadata:
    section: pe
  deprec:
    compiler: llvm@11.0.1
    python:
      2: 2.7.18
      3: 3.9.11
    mpi: mvapich2@2.3.4
    blas: openblas@0.3.15
    gpu:
      nvidia: cuda@0.1
      amd: rocm@0.2
  stable:
    compiler: llvm@13.0.1
    mpi: mvapich2@2.3.7
    blas: openblas@0.3.18
    gpu:
      nvidia: cuda@1
      amd: rocm@2
    python: python@3.7.7 +tkinter +optimization
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                             #
# PACKAGES SECTION                                                            #
#                                                                             #
# The packages in the following list will be compiled                         #
# with the system compiler (also known as the core compiler).                 #
# These are packages that need simple or no dependencies.                     #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
core_pkgs:
  metadata:
    section: packages
  pe:
  - core
  packages:
  - cmake:
      default:
        version: 3.2.1
        variants:
          gpu:
            nvidia: +cuda cuda_arch=<cuda_arch>
            amd: +rocm
  - autoconf
  - automake:
      dependencies:
      - openssl@1.1.1b
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                             #
# SERIAL PACKAGES                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
serial_pkgs:
  metadata:
    section: packages
  pe:
  - gcc_stable
  - intel_stable
  packages:
  - netcdf-c ~mpi
  - openblas threads=openmp
# O CASO SEGUINTE DEVE CRIAR UMA ENTRADA NO `packages.yaml`
# PARA O `libiconv`
  - cuda:
      default:
        version: 10.2.89
        variants:
          dependencies:
          - libiconv
  - cuda@11.0.2
  - cuda@11.1.1
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                             #
# MPI PACKAGES                                                                #
#                                                                             #
# The packages in this list will have MPI for dependency.                     #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
# THE FUNCTION THAT WILL CHOOSE THE GPU FOR THE PACKAGES SECTION WILL HAVE
# A DIFFERENT BEHAVIOUR FROM THE ONE THAT MAKE THE CHOICES IN THE COMPILERS
# CASE. HERE, IN THE PACKAGES SECTION, WE WANT THAT THE CHOOSEN VALUE BE
# ADDED TO THE PACKAGE VARIANT.
#
# CREATE TWO DICTS, ONE TO FEED SPACK.YAML AND THE SECOND TO FEED PACKAGES.YAML.
# FOR PKG IN PACKAGES:
#   IF PKG IS DICT:
#     RETURN `FULL_PACKAGE_VARIANT` INCLUDING `TOKEN SELECTION` (SINGLE LINE)
#     IF DEFAULT IN PKG:
#       ADD TO DICTIONARY IN A FORM THAT GOES TO PACKAGES.YAML (INCLUDING `TOKEN SELECTION`)
#   RETURN STR
mpi_pkgs:
  metadata:
    # PROCESS THIS SECTION AS A PACKAGES
    section: packages
  # USE THE COMPILERS AND LIBARIES DEFINED IN THIS ENVIRONMENT
  pe:
  - gcc_stable
  # MAKE EXPLICIT DEPENDENCY IN MATRIX
  dependencies:
  - mpi
  # INSTALL THE FOLLOWING PACKAGES
  packages:
  - lmod                                                                     
  # ADD SPEC `fftw@3.3.8 +mpi+openmp` TO `mpi_pkgs` PACKAGE LIST             
  # WRITE THE SPEC IN `packages.yaml`
  # fftw:
  #   version: 3.3.8
  #   variants: +mpi+openmp
  - fftw:
      default:
        variants: +mpi+openmp
        version: 3.3.8
  - fftw ~mpi~openmp
  # ADD SPEC `hdf5 +szip+mpi+hl+fortran+cxx+cuda/~cuda` TO `mpi_pkgs` PACKAGE LIST
  # WRITE THE SPEC IN `packages.yaml`
  # hdf5:
  #   varaints: +szip+mpi+hl+fortran+cxx+cuda/~cuda
  - hdf5:
      default: 
        variants: +szip+mpi+hl+fortran+cxx
        gpu:
          nvidia: +cuda
          none: ~cuda
  - netcdf-c +mpi
  - netcdf-fortran
  - gpu:
      nvidia: +cuda
      none: ~cuda
  # ADD SPEC `pkg +mpi+cuda/~cuda` TO `mpi_pkgs` PACKAGE LIST
  # DOES NOTHING IN `packages.yaml`
  - pkg:
      variants: '@2.18 +mpi'
      dependencies:
      - libiconv
      - libgreat
      gpu:
        nvidia: +cuda cuda_arch=<cuda_arch>
        nogpu: ~cuda
      default:
        version: 2.18
        variants: +mpi
        mpi:
          ethernet: opt1
          infiniband: opt2
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                             #
# MPI + BLAS PACKAGES                                                         #
#                                                                             #
# The packages in this list will have MPI and BLAS for dependency.            #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
mpi_blas_pkgs:
  metadata:
    section: packages
  pe:
  - gcc_stable
  - llvm_deprecated
  dependencies:
  - mpi
  - blas
  packages:
  - gmsh +openmp+hdf5
  - hypre +cuda cuda_arch=<cuda_arch>
  - scotch +esmumps+mpi~metis
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                             #
# PYTHON SECTION                                                              #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
#                                                                             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# python_packages:
# - mercurial
# - ninja
# - py-pybind11
# - py-pybigwig
