export VERSION=v1
export ROOT_DIR=/home/scitasbuildpr
export PYTHON_VIRTUALENV_PATH=${ROOT_DIR}/${STACK_RELEASE}/py3-venv
export JENKINS_SCRIPTS_PATH=jenkins/deploy/scripts
export STACK_RELEASE=syrah
export STACK_PREFIX=${ROOT_DIR}/${STACK_RELEASE}
export SPACK_RELEASE=v0.18.1
export SPACK_SDPLOY_PATH=spack-sdploy
export SPACK_SDPLOY_INSTALL_PATH=${STACK_PREFIX}/${SPACK_SDPLOY_PATH}
export SPACK_CONFIG_PATH=spack-config
export SPACK_USER_CONFIG_PATH=${STACK_PREFIX}/${SPACK_CONFIG_PATH}
export SPACK_SDPLOY_INSTALL_PATH=${STACK_PREFIX}/${SPACK_SDPLOY_PATH}
export SPACK_PREFIX=${STACK_PREFIX}/${SPACK_SDPLOY_PATH}
export SPACK_INSTALL_PATH=${STACK_PREFIX}/spack.${VERSION}

# echo === Exported variables ===
# echo VERSION: ${VERSION}
# echo SPACK_RELEASE: ${SPACK_RELEASE}
# echo SPACK_SDPLOY_PATH: ${SPACK_SDPLOY_PATH}
# echo SPACK_SDPLOY_INSTALL_PATH: ${SPACK_SDPLOY_INSTALL_PATH}
# echo SPACK_CONFIG_PATH: ${SPACK_CONFIG_PATH}
# echo SPACK_USER_CONFIG_PATH: ${SPACK_USER_CONFIG_PATH}
# echo SPACK_SDPLOY_INSTALL_PATH: $SPACK_SDPLOY_INSTALL_PATH
# echo SPACK_INSTALL_PATH: $SPACK_INSTALL_PATH
# echo PATH: $PATH
